s/etckeeper/usrkeeper/g
For reference:

find . -type f \! -path '*/.git/*' \! -path './debian/po/de.po' -print0 | xargs -0 -n 1 sed -i '' 's/etckeeper/usrkeeper/g'
find . -name '*etckeeper*' -print | tail -r | xargs -n 1 -I % bash -c 'git mv % $(dirname %)/$(basename % | sed "s/etckeeper/usrkeeper/g" )'

See http://unix.stackexchange.com/q/282354/29146 for how the
latter command works.

diff --git a/commit.d/30bzr-add b/commit.d/30bzr-add
--- a/commit.d/30bzr-add
+++ b/commit.d/30bzr-add
@@ -3,6 +3,6 @@ set -e
 
 if [ "$VCS" = bzr ] && [ -d .bzr ]; then
 	if ! bzr add -q .; then
-		echo "etckeeper warning: bzr add failed" >&2
+		echo "usrkeeper warning: bzr add failed" >&2
 	fi
 fi
diff --git a/commit.d/30darcs-add b/commit.d/30darcs-add
--- a/commit.d/30darcs-add
+++ b/commit.d/30darcs-add
@@ -7,7 +7,7 @@ if [ "$VCS" = darcs ] && [ -d _darcs ]; then
 	if test $rc -ne 0; then
 		if ! test $rc -eq 2 -a "${res%No files were added}" != "$res"; then
 			printf "%s" "$res"
-			echo "etckeeper warning: darcs add failed" >&2
+			echo "usrkeeper warning: darcs add failed" >&2
 		fi
 	fi
 	unset rc res
diff --git a/commit.d/30hg-addremove b/commit.d/30hg-addremove
--- a/commit.d/30hg-addremove
+++ b/commit.d/30hg-addremove
@@ -3,6 +3,6 @@ set -e
 
 if [ "$VCS" = hg ] && [ -d .hg ]; then
 	if ! hg addremove .; then
-		echo "etckeeper warning: hg addremove failed" >&2
+		echo "usrkeeper warning: hg addremove failed" >&2
 	fi
 fi
diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -21,78 +21,78 @@ mv_conffile() {
 case "$1" in
 configure)
 	if dpkg --compare-versions "$2" le "0.7"; then
-		if [ -d /etc/etckeeper/pre-apt.d ]; then
-			mv_conffile "/etc/etckeeper/pre-apt.d/README" \
-				"/etc/etckeeper/pre-install.d/README"
-			mv_conffile "/etc/etckeeper/pre-apt.d/50uncommitted-changes" \
-				"/etc/etckeeper/pre-install.d/50uncommitted-changes"
-			rmdir --ignore-fail-on-non-empty /etc/etckeeper/pre-apt.d
+		if [ -d /etc/usrkeeper/pre-apt.d ]; then
+			mv_conffile "/etc/usrkeeper/pre-apt.d/README" \
+				"/etc/usrkeeper/pre-install.d/README"
+			mv_conffile "/etc/usrkeeper/pre-apt.d/50uncommitted-changes" \
+				"/etc/usrkeeper/pre-install.d/50uncommitted-changes"
+			rmdir --ignore-fail-on-non-empty /etc/usrkeeper/pre-apt.d
 		fi
-		if [ -d /etc/etckeeper/post-apt.d ]; then
-			mv_conffile "/etc/etckeeper/post-apt.d/README" \
-				"/etc/etckeeper/post-install.d/README"
-			mv_conffile "/etc/etckeeper/post-apt.d/10git-test" \
-				"/etc/etckeeper/post-install.d/10vcs-test"
-			mv_conffile "/etc/etckeeper/post-apt.d/30git-add" \
-				"/etc/etckeeper/post-install.d/30git-add"
-			mv_conffile "/etc/etckeeper/post-apt.d/40git-rm" \
-				"/etc/etckeeper/post-install.d/40git-rm"
-			mv_conffile "/etc/etckeeper/post-apt.d/50git-commit" \
-				"/etc/etckeeper/post-install.d/50vcs-commit"
-			rmdir --ignore-fail-on-non-empty /etc/etckeeper/post-apt.d
+		if [ -d /etc/usrkeeper/post-apt.d ]; then
+			mv_conffile "/etc/usrkeeper/post-apt.d/README" \
+				"/etc/usrkeeper/post-install.d/README"
+			mv_conffile "/etc/usrkeeper/post-apt.d/10git-test" \
+				"/etc/usrkeeper/post-install.d/10vcs-test"
+			mv_conffile "/etc/usrkeeper/post-apt.d/30git-add" \
+				"/etc/usrkeeper/post-install.d/30git-add"
+			mv_conffile "/etc/usrkeeper/post-apt.d/40git-rm" \
+				"/etc/usrkeeper/post-install.d/40git-rm"
+			mv_conffile "/etc/usrkeeper/post-apt.d/50git-commit" \
+				"/etc/usrkeeper/post-install.d/50vcs-commit"
+			rmdir --ignore-fail-on-non-empty /etc/usrkeeper/post-apt.d
 		fi
-		mv_conffile "/etc/etckeeper/init.d/40git-init" \
-			"/etc/etckeeper/init.d/40vcs-init"
-		mv_conffile "/etc/etckeeper/init.d/50git-ignore" \
-			"/etc/etckeeper/init.d/50vcs-ignore"
-		mv_conffile "/etc/etckeeper/init.d/50git-perm" \
-			"/etc/etckeeper/init.d/50vcs-perm"
-		mv_conffile "/etc/etckeeper/init.d/50git-pre-commit-hook" \
-			"/etc/etckeeper/init.d/50vcs-pre-commit-hook"
-		mv_conffile "/etc/etckeeper/init.d/70git-add" \
-			"/etc/etckeeper/init.d/70git-add"
+		mv_conffile "/etc/usrkeeper/init.d/40git-init" \
+			"/etc/usrkeeper/init.d/40vcs-init"
+		mv_conffile "/etc/usrkeeper/init.d/50git-ignore" \
+			"/etc/usrkeeper/init.d/50vcs-ignore"
+		mv_conffile "/etc/usrkeeper/init.d/50git-perm" \
+			"/etc/usrkeeper/init.d/50vcs-perm"
+		mv_conffile "/etc/usrkeeper/init.d/50git-pre-commit-hook" \
+			"/etc/usrkeeper/init.d/50vcs-pre-commit-hook"
+		mv_conffile "/etc/usrkeeper/init.d/70git-add" \
+			"/etc/usrkeeper/init.d/70git-add"
 	fi
 	if dpkg --compare-versions "$2" le "0.10"; then
         	for c in 10vcs-test 30git-add 30hg-addremove 40git-rm; do
-			mv_conffile "/etc/etckeeper/post-install.d/$c" \
-				"/etc/etckeeper/commit.d/$c"
+			mv_conffile "/etc/usrkeeper/post-install.d/$c" \
+				"/etc/usrkeeper/commit.d/$c"
 
 		done
 	fi
 	if dpkg --compare-versions "$2" le "0.13"; then
-		mv_conffile "/etc/etckeeper/init.d/10restore-etckeeper" \
-			"/etc/etckeeper/init.d/20restore-etckeeper"
-		mv_conffile "/etc/etckeeper/init.d/20restore-metadata" \
-			"/etc/etckeeper/init.d/10restore-metadata"
+		mv_conffile "/etc/usrkeeper/init.d/10restore-usrkeeper" \
+			"/etc/usrkeeper/init.d/20restore-usrkeeper"
+		mv_conffile "/etc/usrkeeper/init.d/20restore-metadata" \
+			"/etc/usrkeeper/init.d/10restore-metadata"
 	fi
 	if dpkg --compare-versions "$2" le "0.28"; then
 		for c in commit.d/30darcs-add init.d/60darcs-deleted-symlinks; do
-			if [ -e /etc/etckeeper/$c ]; then
-				chmod +x /etc/etckeeper/$c
+			if [ -e /etc/usrkeeper/$c ]; then
+				chmod +x /etc/usrkeeper/$c
 			fi
 		done
 	fi
 	if dpkg --compare-versions "$2" le "0.61"; then
 		# may be left over from a botched conffile removal
-		rm -f /etc/etckeeper/commit.d/40git-rm.dpkg-dist
+		rm -f /etc/usrkeeper/commit.d/40git-rm.dpkg-dist
 	fi
 
-	if [ "$2" = "" ] && [ -e "/etc/etckeeper/etckeeper.conf" ]; then
+	if [ "$2" = "" ] && [ -e "/etc/usrkeeper/usrkeeper.conf" ]; then
 		# Fresh install.
-		. /etc/etckeeper/etckeeper.conf || true
+		. /etc/usrkeeper/usrkeeper.conf || true
 		if [ -n "$VCS" ] && [ -x "`which $VCS 2>/dev/null`" ]; then
-			if etckeeper init; then
-				if ! etckeeper commit "Initial commit"; then
-					echo "etckeeper commit failed; run it by hand" >&2
+			if usrkeeper init; then
+				if ! usrkeeper commit "Initial commit"; then
+					echo "usrkeeper commit failed; run it by hand" >&2
 				fi
 			else
-				echo "etckeeper init failed; run it by hand" >&2
+				echo "usrkeeper init failed; run it by hand" >&2
 			fi
 		else
-			echo "etckeeper init not ran as $VCS is not installed" >&2
+			echo "usrkeeper init not ran as $VCS is not installed" >&2
 		fi
 	fi
 
 	# prints error and exits nonzero if the ignore file cannot be updated
-	etckeeper update-ignore || true
+	usrkeeper update-ignore || true
 esac
diff --git a/init.d/70vcs-add b/init.d/70vcs-add
--- a/init.d/70vcs-add
+++ b/init.d/70vcs-add
@@ -3,15 +3,15 @@ set -e
 
 if [ "$VCS" = git ]; then
 	if ! git add .; then
-		echo "etckeeper warning: git add failed" >&2
+		echo "usrkeeper warning: git add failed" >&2
 	fi
 elif [ "$VCS" = hg ]; then
 	if ! hg add .; then
-		echo "etckeeper warning: hg add failed" >&2
+		echo "usrkeeper warning: hg add failed" >&2
 	fi
 elif [ "$VCS" = bzr ]; then
 	if ! bzr add .; then
-		echo "etckeeper warning: bzr add failed" >&2
+		echo "usrkeeper warning: bzr add failed" >&2
 	fi
 elif [ "$VCS" = darcs ]; then
 	# Don't warn if all the files were already added.
@@ -20,7 +20,7 @@ elif [ "$VCS" = darcs ]; then
 	if test $rc -ne 0; then
 		if ! test $rc -eq 2 -a "${res%No files were added}" != "$res"; then
 			printf "%s" "$res"
-			echo "etckeeper warning: darcs add failed" >&2
+			echo "usrkeeper warning: darcs add failed" >&2
 		fi
 	fi
 	unset rc res
diff --git a/post-install.d/50vcs-commit b/post-install.d/50vcs-commit
--- a/post-install.d/50vcs-commit
+++ b/post-install.d/50vcs-commit
@@ -1,27 +1,27 @@
 #!/bin/sh
 set -e
 
-pl="/var/cache/etckeeper/packagelist"
+pl="/var/cache/usrkeeper/packagelist"
 
-if etckeeper unclean; then
+if usrkeeper unclean; then
 	message="committing changes in /etc after $HIGHLEVEL_PACKAGE_MANAGER run"
 
 	set +e
-	if [ -e $pl.pre-install ] && [ "$(cat $pl.fmt 2>/dev/null || true)" = "$(etckeeper list-installed fmt)" ]; then
+	if [ -e $pl.pre-install ] && [ "$(cat $pl.fmt 2>/dev/null || true)" = "$(usrkeeper list-installed fmt)" ]; then
 		(
 			echo "$message"
 			echo
 			echo "Package changes:"
-			etckeeper list-installed | diff -U0 $pl.pre-install - | tail -n+4 | egrep '^[-+]' || true
-		) | etckeeper commit --stdin
+			usrkeeper list-installed | diff -U0 $pl.pre-install - | tail -n+4 | egrep '^[-+]' || true
+		) | usrkeeper commit --stdin
 	else
-		etckeeper commit "$(printf "$message")"
+		usrkeeper commit "$(printf "$message")"
 	fi
 	status=$?
 	set -e
 
 	if [ "$status" != 0 ]; then
-		echo "warning: etckeeper failed to commit changes in /etc using $VCS" >&2
+		echo "warning: usrkeeper failed to commit changes in /etc using $VCS" >&2
 	fi
 fi
 	
diff --git a/uninit.d/50vcs-uninit b/uninit.d/50vcs-uninit
--- a/uninit.d/50vcs-uninit
+++ b/uninit.d/50vcs-uninit
@@ -15,9 +15,9 @@ elif [ "$VCS" = darcs ]; then
 	file=.darcsignore
 fi
 
-managed_by_etckeeper="managed by etckeeper"
+managed_by_usrkeeper="managed by usrkeeper"
 
-if ! grep -q "$managed_by_etckeeper" "$file"; then
+if ! grep -q "$managed_by_usrkeeper" "$file"; then
 	exit 0
 else
 	realfile="$file"
@@ -26,14 +26,14 @@ else
 	elif which mktemp >/dev/null 2>&1 || type mktemp >/dev/null 2>&1; then
 		tempfile="mktemp"
 	else
-		echo "etckeeper warning: can't find tempfile or mktemp" >&2
+		echo "usrkeeper warning: can't find tempfile or mktemp" >&2
 		exit 1
 	fi
 	file=$($tempfile)
 	otherentries=
 	skipping=
 	while read -r line; do
-		if echo "$line" | grep -q "$managed_by_etckeeper"; then
+		if echo "$line" | grep -q "$managed_by_usrkeeper"; then
 			if [ ! "$skipping" ]; then
 				skipping=1
 			else
diff --git a/usrkeeper b/usrkeeper
--- a/usrkeeper
+++ b/usrkeeper
@@ -2,13 +2,13 @@
 set -e
 
 if [ -z "$ETCKEEPER_CONF_DIR" ]; then
-	ETCKEEPER_CONF_DIR=/etc/etckeeper
+	ETCKEEPER_CONF_DIR=/etc/usrkeeper
 fi
 
-conf="$ETCKEEPER_CONF_DIR/etckeeper.conf"
+conf="$ETCKEEPER_CONF_DIR/usrkeeper.conf"
 
 usage() {
-	echo "usage: etckeeper command [-d directory]" >&2
+	echo "usage: usrkeeper command [-d directory]" >&2
 	exit 1
 }
 
@@ -67,7 +67,7 @@ fi
 if [ -z "$1" ]; then
 	usage
 elif [ "x$1" = "x-h" ] || [ "x$1" = "x--help" ]; then
-	man etckeeper || echo "Usage: etckeeper command [-d directory]" >&2
+	man usrkeeper || echo "Usage: usrkeeper command [-d directory]" >&2
 	exit 0
 elif [ "x$1" = "x-v" ] || [ "x$1" = "x--version" ]; then
 	# This is automatically updated by the Makefile.
@@ -85,12 +85,12 @@ elif [ "$command" = "pre-apt" ]; then
 fi
 
 if echo "$command" | LANG=C egrep -q '[^-a-z_]'; then
-	echo "etckeeper: invalid command $command" >&2
+	echo "usrkeeper: invalid command $command" >&2
 	exit 1
 fi
 
 if [ ! -d "$ETCKEEPER_CONF_DIR/$command.d" ]; then
-	echo "etckeeper: $ETCKEEPER_CONF_DIR/$command.d does not exist" >&2
+	echo "usrkeeper: $ETCKEEPER_CONF_DIR/$command.d does not exist" >&2
 	exit 1
 fi
 
